on: pull_request_target

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

name: Pull Request updated

jobs:
  history:
    name: Pull Request Body
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: workflow-settings.json, workflow-details.json
          IGNORE_WARNING: 'true'
      - uses: technote-space/pr-commit-body-action@gh-actions
        with:
          TITLE: "## 커밋 📝"
          LINK_ISSUE_KEYWORD: ${{ (startsWith(github.head_ref, 'release/') && 'closes') || '' }}
          FILTER_PR: true
          CHANGE_TEMPLATE: "- [ ] ${TITLE} (#${NUMBER}) @${AUTHOR}"