name: Pull Request updated

on: pull_request_target

jobs:
  history:
    name: Pull Request Body
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    steps:
      - uses: technote-space/pr-commit-body-action@gh-actions
        with:
          FILTER_PR: true
          CHANGE_TEMPLATE: "- [ ] ${TITLE} (#${NUMBER}) @${AUTHOR}"